### ISSUE TITLE
🐛 Fix peers having duplicated shared connections

### ISSUE THREAD

**Issue by BertrandD** [Hyle-org/hyle#902]
When peer A & B have each other in their `peers` conf, they each try to establish a tcp connection with the other. It results with having 2 active tcp connection between them, where a single one is required. The issue is when consensus is broadcasting a message, the other peer receives the message twice.

**Comment by hey-ewan** [comment]
@BertrandD how do I reproduce this?

**Comment by BertrandD** [comment]
You basically needs to run 2 nodes with consensus. So you can create 2 dirs with a different conf. 

- file `node1/config.toml`:
```toml
id = "node-1"
port = 1231
tcp_server_port = 1414
rest_server_port = 4321
da_server_port = 4141
data_directory = "data"
run_indexer = false

[p2p]
server_port = 1231
peers = ["127.0.0.1:1232"]

[consensus]
solo = false

[genesis]
stakers = { "node-1" = 100, "node-2" = 100 }

```
- file `node2/config.toml`
```toml
id = "node-2"
port = 1232
tcp_server_port = 1415
rest_server_port = 4322
da_server_port = 4142
data_directory = "data"
run_indexer = false

[p2p]
server_port = 1232
peers = ["127.0.0.1:1231"]

[consensus]
solo = false

[genesis]
stakers = { "node-1" = 100, "node-2" = 100 }

```


then in node1 folder run `cargo run `
and in node2 folder run `RUST_LOG=info,hyle::p2p::peer=trace cargo run`

the 2 nodes should connect to each other & start consensus.

On the 2nd node you will have more logs, you will be able to see those:
```
2025-03-28T16:32:31.602038Z TRACE hyle::p2p::peer: Broadcast message to #1: NetMessage::ConsensusMessage  --> from validator a0eb2f
2025-03-28T16:32:31.602213Z TRACE hyle::p2p::peer: Broadcast message to #2: NetMessage::ConsensusMessage  --> from validator a0eb2f
```

and the problem is that the message got broadcasted twice as the 2 peers are identical. 

We need to keep a map of peers and only add a peer once on connection when we do not know it.
